name: "cachix-action test"
on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - uses: cachix/install-nix-action@v2
    - name: Test public cache
      uses: ./
      with:
        push: cachix-action
        file: test.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Test private cache
      uses: ./
      with:
        push: cachix-action-private
        file: test.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY_PRIVATE }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'